[package]
name = "common"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3 = { version = "1.5.1", default-features = false, features = ["digest"] }
borsh.workspace = true
rand_chacha = "0.3.1"
rand_core = { version = "0.6.4", features = ["getrandom"] }
tai64 = "4.0.0"
